name: CI

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v5
        with:
          version: latest

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"

      - name: 依存関係のインストール
        run: pnpm install --frozen-lockfile

      - name: Prisma Client 生成
        run: pnpm db:generate

      - name: リント
        run: pnpm lint

      - name: 型チェック
        run: pnpm typecheck

      - name: テスト実行
        run: pnpm test
